'use server';

/**
 * @fileOverview An AI agent for enhancing image quality.
 *
 * - enhanceImageQuality - A function that enhances the quality of an image up to 16K and provides a before-and-after comparison.
 * - EnhanceImageQualityInput - The input type for the enhanceImageQuality function.
 * - EnhanceImageQualityOutput - The return type for the enhanceImageQuality function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceImageQualityInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo to be enhanced, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type EnhanceImageQualityInput = z.infer<typeof EnhanceImageQualityInputSchema>;

const EnhanceImageQualityOutputSchema = z.object({
  enhancedImageGemini: z
    .string()
    .describe('The enhanced image generated by Gemini, as a data URI.'),
  enhancedImageOpenAI: z
    .string()
    .describe('The enhanced image generated by OpenAI, as a data URI.'),
});
export type EnhanceImageQualityOutput = z.infer<typeof EnhanceImageQualityOutputSchema>;

export async function enhanceImageQuality(input: EnhanceImageQualityInput): Promise<EnhanceImageQualityOutput> {
  return enhanceImageQualityFlow(input);
}

const enhanceImageQualityPromptGemini = ai.definePrompt({
  name: 'enhanceImageQualityPromptGemini',
  input: {schema: EnhanceImageQualityInputSchema},
  output: {schema: z.string().describe('The enhanced image as a data URI.')},
  prompt: `Enhance the quality of the following image to the highest possible resolution, up to 16K, using Gemini:

  {{media url=photoDataUri}}
  `,
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const enhanceImageQualityPromptOpenAI = ai.definePrompt({
  name: 'enhanceImageQualityPromptOpenAI',
  input: {schema: EnhanceImageQualityInputSchema},
  output: {schema: z.string().describe('The enhanced image as a data URI.')},
  prompt: `Enhance the quality of the following image to the highest possible resolution, up to 16K, using OpenAI:

  {{media url=photoDataUri}}
  `,
  config: {
    safetySettings: [
      {
        category: 'HARM_CATEGORY_HATE_SPEECH',
        threshold: 'BLOCK_ONLY_HIGH',
      },
      {
        category: 'HARM_CATEGORY_DANGEROUS_CONTENT',
        threshold: 'BLOCK_NONE',
      },
      {
        category: 'HARM_CATEGORY_HARASSMENT',
        threshold: 'BLOCK_MEDIUM_AND_ABOVE',
      },
      {
        category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT',
        threshold: 'BLOCK_LOW_AND_ABOVE',
      },
    ],
  },
});

const enhanceImageQualityFlow = ai.defineFlow(
  {
    name: 'enhanceImageQualityFlow',
    inputSchema: EnhanceImageQualityInputSchema,
    outputSchema: EnhanceImageQualityOutputSchema,
  },
  async input => {
    // Generate the enhanced image using Gemini.
    const geminiResult = await ai.generate({
      prompt: [      
        {media: {url: input.photoDataUri}},
        {text: enhanceImageQualityPromptGemini.prompt}],
        model: 'googleai/gemini-2.0-flash-preview-image-generation',
        config: {
          responseModalities: ['TEXT', 'IMAGE'], // MUST provide both TEXT and IMAGE, IMAGE only won't work
        },
    });
    const enhancedImageGemini = geminiResult.media?.url ?? 'no image generated';

    // Generate the enhanced image using OpenAI.
    const openAIResult = await ai.generate({
      prompt: [      
        {media: {url: input.photoDataUri}},
        {text: enhanceImageQualityPromptOpenAI.prompt}],
        model: 'googleai/gemini-2.0-flash-preview-image-generation',
        config: {
          responseModalities: ['TEXT', 'IMAGE'], // MUST provide both TEXT and IMAGE, IMAGE only won't work
        },
    });
    const enhancedImageOpenAI = openAIResult.media?.url ?? 'no image generated';

    return {
      enhancedImageGemini,
      enhancedImageOpenAI,
    };
  }
);
